### ISSUE TITLE
Not compiling with rollup

### ISSUE THREAD

**Issue by hollowdoor** [webdeveric/animation-frame-polyfill#1]
rollup doesn't want to transpile 3rd party dependencies.

Seems the author of rollup doesn't like the idea of transpiling 3rd party dependencies -- which I tend to agree.

https://github.com/rollup/rollup-plugin-babel/issues/30

When I import `animation-frame-polyfill` rollup transpiles the module syntax only.

If you don't mind would you make `jsnext:main` point to a es5 transpiled version for this lib? Keeping the es6 module syntax of course.

**Comment by webdeveric** [comment]
@hollowdoor I've updated the build scripts in the `dev` branch. Try it out.

**Comment by hollowdoor** [comment]
It builds nicely with rollup. You don't have to use the compact option for the build:module script though. I don't know if debugging will be hindered by a third party compacted module.

**Comment by hollowdoor** [comment]
Awesome! So far this is the only library I've found on npm that looks like it handles all cases, and doesn't pollute the global scope. I was almost ready to make my own. :)
